djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from reservas import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('reserva/', views.reserva, name='reserva'),
    path('reserva/reservar_habitacion/<int:habitacion_id>/', views.reservar_habitacion, name='reservar_habitacion'),
    path('punto_venta/', views.punto_venta, name='punto_venta'),
    path('facturas/', views.facturas, name='facturas'),
    path('facturas/factura_pdf/<int:reserva_id>/', views.factura_pdf, name='factura_pdf'),
    path('facturas/fact/<int:reserva_id>/', views.fact, name='fact'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('informacion_hotel/', views.informacion_hotel, name='informacion_hotel'),
    path('habitaciones/', views.habitaciones, name='habitaciones'),
    path('habitaciones/editar_habitacion/<int:habitacion_id>/', views.editar_habitacion, name='editar_habitacion'),
    path('habitaciones/eliminar_habitacion/<int:habitacion_id>/', views.eliminar_habitacion, name='eliminar_habitacion'),
    path('perfil/', views.perfil, name='perfil'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('obtener_cliente/<int:habitacion_id>/', views.obtener_cliente, name='obtener_cliente'),
    path('editar_usuario/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('editar_usuario/cambiar_password/<int:usuario_id>/', views.cambiar_password, name='cambiar_password'),
    path('eliminar_usuario/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('agregar_usuarios/', views.agregar_usuarios, name='agregar_usuarios'),
]

reservas/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.

class UsuarioManager(BaseUserManager):
    def create_user(self, cedula, first_name, last_name, fecha_de_nacimiento, genero, email, username, telefono, cargo, password=None):
        if not email:
            raise ValueError('El usuario debe tener un correoelectronico!')

        user = self.model(
            cedula = cedula,
            first_name = first_name,
            last_name = last_name,
            fecha_de_nacimiento = fecha_de_nacimiento,
            genero = genero,
            email = self.normalize_email(email),
            username = username,
            telefono = telefono,
            cargo = cargo,
        )
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self, cedula, first_name, last_name, fecha_de_nacimiento, genero, email, username, telefono, cargo, password):
        user = self.create_user(
            cedula = cedula,
            first_name = first_name,
            last_name = last_name,
            fecha_de_nacimiento = fecha_de_nacimiento,
            genero = genero,
            email = email,
            username = username,
            telefono = telefono,
            cargo = cargo,
            password = password,
        )
        user.user_admin = True
        user.is_staff = True
        user.save()
        return user


class Usuario(AbstractBaseUser):
    # datos personales
    cedula = models.CharField(max_length=10, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    fecha_de_nacimiento = models.DateField()
    OPCIONES_GENERO = [
        ('', '-----'),
        ('FEMENINO', 'FEMENINO'),
        ('MASCULINO', 'MASCULINO'),
    ]
    genero = models.CharField(max_length=10, choices=OPCIONES_GENERO)

    # datos de la cuenta
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    telefono = models.CharField(max_length=15)

    # datos del empleo
    fecha_de_ingreso = models.DateTimeField(auto_now=True)
    OPCIONES_ROL = [
        ('', '-----'),
        ('GERENTE', 'GERENTE'),
        ('ADMINISTRADOR', 'ADMINISTRADOR'),
        ('EMPLEADO', 'EMPLEADO')
    ]
    cargo = models.CharField(max_length=13, choices=OPCIONES_ROL)
    last_login = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    user_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = [
        'cedula', 'first_name', 'last_name', 'fecha_de_nacimiento', 'genero', 'email', 'telefono', 'fecha_de_ingreso', 'cargo'
    ]

    objects = UsuarioManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def if_staff(self):
        return self.user_admin


class Hotel(models.Model):
    nombre = models.CharField(max_length=255)
    telefono = models.CharField(max_length=20)
    correo = models.EmailField()
    ubicacion = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre


class Habitacion(models.Model):
    nombre = models.CharField(max_length=100)
    numero = models.IntegerField(default=0)
    precio = models.FloatField(default=0)
    reservada = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.nombre} - No.{self.numero}'


class Reserva(models.Model):
    cedula = models.CharField(max_length=20)
    cliente = models.CharField(max_length=50)
    telefono = models.CharField(max_length=20)
    email = models.EmailField()
    tipo_cliente = models.CharField(max_length=20)
    habitacion = models.ForeignKey(Habitacion, on_delete=models.CASCADE)
    fecha_reserva = models.DateField()
    precio_habitacion = models.FloatField(default=0)
    tiempo = models.FloatField(default=0)
    tipo_pago = models.CharField(max_length=20)
    numero_tarjeta = models.CharField(max_length=30, default=None)
    total_pagar = models.FloatField(default=0)
    reserva_terminada = models.BooleanField(default=False)

    def __str__(self):
        return f'Habitación {self.habitacion} reservada por {self.cliente}'


class Pedido(models.Model):
    habitacion = models.ForeignKey(Habitacion, on_delete=models.CASCADE)
    cliente = models.CharField(max_length=50)
    producto = models.CharField(max_length=50)
    precio = models.FloatField(default=0)
    cantidad = models.IntegerField(default=0)
    tipo_pago = models.CharField(max_length=20)
    numero_tarjeta = models.CharField(max_length=30, default=None)
    total_pagar = models.FloatField(default=None)

    def __str__(self):
        return f'{self.producto} pedido por {self.cliente} en habitacion No.{self.habitacion}'

reservas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db import IntegrityError
from django.http import HttpResponse, JsonResponse
from .models import Hotel, Habitacion, Reserva, Pedido, Usuario
from .forms import HotelForm, HabitacionForm, ReservaForm, PedidoForm, RegistroForm, LoginForm, CambiarPasswordForm
from io import BytesIO
from xhtml2pdf import pisa


# Create your views here.
def home(request):
    return render(request, 'index.html')


def signup(request):
    if request.method == 'POST':
        registroForm = RegistroForm(request.POST)
        if registroForm.is_valid():
            cedula = registroForm.cleaned_data['cedula']
            first_name = registroForm.cleaned_data['first_name']
            last_name = registroForm.cleaned_data['last_name']
            fecha_de_nacimiento = registroForm.cleaned_data['fecha_de_nacimiento']
            genero = registroForm.cleaned_data['genero']
            email = registroForm.cleaned_data['email']
            telefono = registroForm.cleaned_data['telefono']
            cargo = registroForm.cleaned_data['cargo']

            username = registroForm.cleaned_data['username']
            password1 = registroForm.cleaned_data['password1']
            password2 = registroForm.cleaned_data['password2']

            if password1 == password2:
                try:
                    user = Usuario.objects.create_user(
                        cedula=cedula,
                        first_name=first_name,
                        last_name=last_name,
                        fecha_de_nacimiento=fecha_de_nacimiento,
                        genero=genero,
                        email=email,
                        username=username,
                        telefono=telefono,
                        cargo=cargo,
                        password=password1,
                    )
                    user.save()
                    login(request, user)
                    return redirect('reserva')
                except IntegrityError:
                    return render(request, 'signin.html', {
                        'form': LoginForm(),
                        'error_message': 'Username ya existe!.'
                    })
            else:
                return HttpResponse('Las contraseñas no coinciden!')
        else:
            return HttpResponse(f"Formulario no válido: {registroForm.errors}")
    else:
        registroForm = RegistroForm()
        return render(request, 'signup.html', {
            'registroForm': registroForm,
        })


def cerrar_sesion(request):
    logout(request)
    return redirect('home')


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {
            'form': LoginForm(),
        })
    else:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('reserva')
        else:
            return render(request, 'signin.html', {
                'form': LoginForm(),
                'error_message': 'Username or password is incorrect.'
            })


def reserva(request):
    habitaciones = Habitacion.objects.all()

    return render(request, 'reserva.html', {
        'habitaciones': habitaciones,
    })


def reservar_habitacion(request, habitacion_id):
    habitacion = get_object_or_404(Habitacion, pk=habitacion_id)

    if request.method == 'POST':
        formReserva = ReservaForm(request.POST)
        if formReserva.is_valid():
            reserva = formReserva.save(commit=False)
            habitacion.reservada = True
            habitacion.save()
            reserva.save()

            return redirect('reserva')
        else:
            return HttpResponse(f"Formulario no válido: {formReserva.errors}")

    else:
        formReserva = ReservaForm()
        return render(request, 'reservar_Habitacion.html', {
            'habitacion': habitacion,
            'formReserva': formReserva,
        })


def punto_venta(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('punto_venta')
        else:
            habitaciones = Habitacion.objects.filter(reservada=True)
            reservas = Reserva.objects.all()
            return render(request, 'punto_venta.html', {
                'form': form,
                'habitaciones': habitaciones,
                'reservas': reservas,
            })
    else:
        habitaciones = Habitacion.objects.filter(reservada=True)
        reservas = Reserva.objects.all()
        form = PedidoForm()
        return render(request, 'punto_venta.html', {
            'form': form,
            'habitaciones': habitaciones,
            'reservas': reservas,
        })


def obtener_cliente(request, habitacion_id):
    reserva = Reserva.objects.filter(habitacion_id=habitacion_id).last()
    cliente = reserva.cliente if reserva else ""
    return JsonResponse({'cliente': cliente})


def factura_pdf(request, reserva_id):
    try:
        # Obtener la reserva del cliente
        reserva_cliente = get_object_or_404(Reserva, pk=reserva_id)

        # Verificar si la habitación asociada a la reserva está reservada
        habitacion_reservada = reserva_cliente.habitacion.reservada

        # Obtener pedidos asociados con el cliente de la reserva
        pedidos = Pedido.objects.filter(cliente=reserva_cliente.cliente)

        # Si la habitación está reservada, aplicar el filtro
        if habitacion_reservada:
            pedidos = pedidos.filter(habitacion=reserva_cliente.habitacion)

        # Obtener todos los hoteles
        hotel = Hotel.objects.all()

        subtotal = reserva_cliente.total_pagar

        for total_pedido in pedidos:
            subtotal += total_pedido.total_pagar

        impuesto = round(subtotal * 0.05, 2)

        monto = subtotal + impuesto

        print(subtotal)
        print(impuesto)
        print(monto)

        fecha_actual = timezone.now().strftime('%d/%m/%Y')

        context_dict = {
            'reserva_cliente': reserva_cliente,
            'hotel': hotel,
            'pedidos': pedidos,
            'subtotal': subtotal,
            'impuesto': impuesto,
            'monto': monto,
            'fecha_actual': fecha_actual,
        }

        template_src = 'factura_pdf.html'
        template = get_template(template_src)
        html = template.render(context_dict)
        result = BytesIO()

        pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)

        if not pdf.err:
            # Llamar a la función de verificación de salida para actualizar el estado de las habitaciones
            verificacion_de_salida(reserva_cliente)
            pedidos.delete()
            reserva_cliente.delete()
            return HttpResponse(result.getvalue(), content_type='application/pdf')

    except Exception as e:
        return HttpResponse(f'Error en la generación de la factura: {e}', status=500)


def verificacion_de_salida(reserva):
    habitaciones_reservadas = Habitacion.objects.filter(reserva=reserva)
    habitaciones_reservadas.update(reservada=False)


def facturas(request):
    # habitacion__reservada=True
    reservas = Reserva.objects.filter()
    if request.method == 'GET' and 'cedula' in request.GET:
        cedula = request.GET['cedula']
        reservas = Reserva.objects.filter(cedula__icontains=cedula)
    else:
        reservas = Reserva.objects.all()
    return render(request, 'facturas.html', {
        'reservas': reservas,
    })


def usuarios(request):
    usuarios = Usuario.objects.all()
    user_log = request.user
    return render(request, 'usuarios.html', {
        'usuarios': usuarios,
        'user_log': user_log
    })


def informacion_hotel(request):
    hotel = Hotel.objects.all().first()

    if request.method == 'POST':
        fromHotel = HotelForm(request.POST, instance=hotel)
        if fromHotel.is_valid():
            hotel = fromHotel.save(commit=False)
            hotel.save()
            return redirect('informacion_hotel')
        else:
            print(f"Formulario no válido: {fromHotel.errors}")
    else:
        fromHotel = HotelForm(instance=hotel)
        return render(request, 'informacion_hotel.html', {
            'hotel': hotel,
            'fromHotel': fromHotel,
        })


def habitaciones(request):
    if request.method == 'POST':
        formHabitacion = HabitacionForm(request.POST)
        if formHabitacion.is_valid():
            habitacion = formHabitacion.save(commit=False)
            habitacion.save()
            return redirect('habitaciones')
        else:
            print(f"Formulario no válido: {formHabitacion.errors}")
    else:
        formHabitacion = HabitacionForm()
        habitaciones = Habitacion.objects.all()

        siguiente_numero_de_habitacione = habitaciones.count() + 1

        return render(request, 'habitaciones.html', {
            'formHabitacion': formHabitacion,
            'habitaciones': habitaciones,
            'siguiente_numero_de_habitacione': siguiente_numero_de_habitacione,
        })


def editar_habitacion(request, habitacion_id):
    habitacion = get_object_or_404(Habitacion, pk=habitacion_id)
    if request.method == 'POST':
        formHabitacion = HabitacionForm(request.POST, instance=habitacion)
        if formHabitacion.is_valid():
            habitacion_editada = formHabitacion.save(commit=False)
            habitacion_editada.save()
            return redirect('habitaciones')
        else:
            return HttpResponse(f"Formulario no válido: {formHabitacion.errors}")
    else:

reservas/templates/editar_habitacion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Luminar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col mt-5">
                <a href="/habitaciones" class="btn btn-success">Atras</a>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <div class="card bg-black text-white w-50 m-5">
                    <div class="card-header text-center bg-black">
                        <h2 class="text-info">Editar habitacion '{{ habitacion.nombre }}'</h2>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'editar_habitacion' habitacion.id %}" method="POST">
                            {% csrf_token %}
                            <label for="id_nombre" class="form-label fw-bolder">Nombre:</label>
                            <input type="text" class="form-control bg-black text-white" name="nombre" required=""
                                value="{{ habitacion.nombre }}" id="id_nombre">

                            <label for="id_numero" class="form-label fw-bolder">Numero:</label>
                            <input type="number" class="form-control bg-black text-white" name="numero" required=""
                                value="{{ habitacion.numero }}" id="id_numero">

                            <label for="id_precio" class="form-label fw-bolder">Precio:</label>
                            <input type="number" class="form-control bg-black text-white" name="precio" required=""
                                value="{{ habitacion.precio }}" id="id_precio">

                            <div class="mt-4 d-flex">
                                <button type="submit" class="btn btn-primary w-50 mx-5">Save changes</button>
                                <button type="button" class="btn btn-danger w-50 mx-5" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-black text-white">
                <div class="modal-body">
                    <p class="text-center">Estas seguro de que quieres eliminar la habitación:</p>
                    <p class="text-center">"{{ habitacion.nombre }} - NO {{ habitacion.numero }}"?</p>
                    
                    <form action="{% url 'eliminar_habitacion' habitacion.id %}" method="POST">
                        {% csrf_token %}
                        <div class="footer d-flex">
                            <button type="button" class="btn btn-outline-secondary w-50 mx-4" data-bs-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-outline-danger w-50 mx-4">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
        </script>

</body>

</html>

reservas/templates/reservar_habitacion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Luminar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col d-flex justify-content-center">
                <div class="card bg-black text-white w-75 m-5">
                    <div class="card-header" style="border-bottom: solid 1px white;">
                        <h2 class="card-title">Registrar nuevo Hospedaje</h2>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'reservar_habitacion' habitacion.id %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_cedula" class="form-label fw-bold">C.Identidad:</label>
                                    <input type="text" class="form-control bg-black text-white border-dark"
                                        name="cedula" maxlength="20" required="" id="id_cedula">
                                </div>

                                <div class="col-6"></div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_cliente" class="form-label fw-bold">Nombres y Apellidos del
                                        cliente</label>
                                    <input type="text" class="form-control bg-black text-white border-dark"
                                        name="cliente" required="" id="id_cliente">
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_telefono" class="form-label fw-bold">Telefono:</label>
                                    <input type="text" class="form-control bg-black text-white border-dark"
                                        name="telefono" maxlength="20" required="" id="id_telefono">
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_email" class="form-label fw-bold">Email:</label>
                                    <input type="email" class="form-control bg-black text-white border-dark"
                                        name="email" maxlength="254" required="" id="id_email">
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_tipo_cliente" class="form-label fw-bold">Tipo cliente:</label>
                                    <select name="tipo_cliente" id="id_tipo_cliente"
                                        class="form-select bg-black text-white border-dark" required="">
                                        <option value="NORMAL">NORMAL</option>
                                        <option value="EMPRESARIO">EMPRESARIO</option>
                                    </select>
                                </div>
                            </div>

                            <div class="row" style="border-top: solid 1px white;">
                                <div class="col-sm-6 mb-3 px-4 pt-3">
                                    <label for="id_habitacion" class="form-label fw-bold">Habitacion:</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-white fw-bold border-dark">No.</span>
                                        <input type="text" class="form-control bg-black text-white border-dark"
                                            name="habitacion" value="{{ habitacion.id }}" required=""
                                            id="id_habitacion">
                                    </div>
                                </div>

                                <div class="col-sm-6 mb-3 px-4 pt-3">
                                    <label for="id_fecha_reserva" class="form-label fw-bold">Fecha reserva:</label>
                                    <input type="date" class="form-control bg-black text-white border-dark"
                                        name="fecha_reserva" required="" id="id_fecha_reserva">
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_precio_habitacion" class="form-label fw-bold">Precio
                                        habitacion:</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-white fw-bold border-dark">$</span>
                                        <input type="number" class="form-control bg-black text-white border-dark"
                                            name="precio_habitacion" value="{{ habitacion.precio }}" readonly=""
                                            id="id_precio_habitacion">
                                    </div>
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_tiempo" class="form-label fw-bold">Tiempo:</label>
                                    <input type="number" class="form-control bg-black text-white border-dark"
                                        name="tiempo" required="" id="id_tiempo">
                                </div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_tipo_pago" class="form-label fw-bold">Tipo pago:</label>
                                    <select name="tipo_pago" id="id_tipo_pago"
                                        class="form-select bg-black text-white border-dark" required="">
                                        <option value="Efectivo">Efectivo</option>
                                        <option value="Tarjeta_de_credito">Tarjeta de crédito</option>
                                    </select>
                                </div>

                                <div class="col-sm-6 mb-3 px-4" id="tarjeta-input-container" style="display: none;">
                                    <label for="id_numero_tarjeta" class="form-label fw-bold">Numero tarjeta:</label>
                                    <input type="text" class="form-control bg-black text-white border-dark"
                                        name="numero_tarjeta" value="None" id="id_numero_tarjeta">
                                </div>

                                <div class="w-100"></div>

                                <div class="col-sm-3 mb-3"></div>

                                <div class="col-sm-6 mb-3 px-4">
                                    <label for="id_total_pagar" class="form-label fw-bold">Total pagar:</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-white fw-bold border-dark">$</span>
                                        <input type="number" class="form-control bg-black text-white border-dark"
                                            name="total_pagar" readonly id="id_total_pagar">
                                    </div>
                                </div>

                                <div class="col-sm-3 mb-3"></div>

                                <hr>

                                <div class="col text-end">
                                    <a href="{% url 'reserva' %}" class="btn btn-danger mx-2">Cancelar</a>
                                    <button class="btn btn-primary" type="submit" id="reservarButton">Agregar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
        </script>

    <script src="{% static 'js/reservar_habitacion.js' %}"></script>

    <script>
        document.getElementById("id_tiempo").addEventListener("input", function () {
            // Obtener el valor del tiempo ingresado
            var tiempoInput = document.getElementById("id_tiempo");
            var tiempoValue = tiempoInput.value;

            // Calcular el total a pagar (suponiendo que hay una tarifa por hora)
            var precioHabitacion = parseFloat("{{ habitacion.precio }}");
            var tiempoFloat = parseFloat(tiempoValue.replace(":", ".")); // Convertir el formato de tiempo a un número
            var totalPagar = precioHabitacion * tiempoFloat;

            // Actualizar el campo "Total pagar"
            var totalPagarInput = document.getElementById("id_total_pagar");
            totalPagarInput.value = totalPagar.toFixed(2); // Redondear a dos decimales
        });
    </script>
</body>

</html>